version: 2

references:
  ubuntu16: &ubuntu16
    docker:
      - image: glotzerlab/ci:2018.09-ubuntu16.04
        environment:
          PYTHONPATH: /home/ci/project/build
    working_directory: /home/ci/project

  ubuntu18: &ubuntu18
    docker:
      - image: glotzerlab/ci:2018.09-ubuntu18.04
        environment:
          PYTHONPATH: /home/ci/project/build
    working_directory: /home/ci/project

  load_code: &load_code
    checkout:
      path: code

  update_submodules: &update_submodules
    run:
      name: Update submodules
      working_directory: code
      command: git submodule update --init

  configure: &configure
    run:
      name: Configure
      command: |
        mkdir build
        cd build
        echo cmake_root=${CMAKE_BIN}
        echo pyver=${PYVER}
        echo cc=${CC}
        echo cxx=${CXX}
        echo enable_cuda=${ENABLE_CUDA}
        echo enable_mpi=${ENABLE_MPI}
        echo enable_tbb=${ENABLE_TBB}
        echo build_validation=${BUILD_VALIDATION}
        echo build_jit=${BUILD_JIT}
        ${CMAKE_BIN}/cmake ../code -DPYTHON_EXECUTABLE=/usr/bin/python${PYVER} -DENABLE_CUDA=${ENABLE_CUDA} -DENABLE_MPI=${ENABLE_MPI} -DENABLE_TBB=${ENABLE_TBB} -DBUILD_VALIDATION=${BUILD_VALIDATION} -DBUILD_JIT=${BUILD_JIT} -DBUILD_DEPRECATED=off -GNinja

  compile: &compile
    run:
      name: Compile
      working_directory: build
      command: ninja -j3

  native_build: &native_build
    steps:
      - *load_code
      - *update_submodules
      - *configure
      - *compile

  build_and_test: &build_and_test
    steps:
      - *load_code
      - *update_submodules
      - *configure
      - *compile
      - run:
          name: Test
          working_directory: build
          no_output_timeout: 2h
          command: ${CMAKE_BIN}/ctest --no-compress-output -T test --output-on-failure
      - run:
          name: Copy test results
          command: mkdir test-results && cp build/Testing/**/Test.xml test-results/
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_test_results:
          path: test-results

jobs:
  gcc48-py27-cm28-mpi-tbb3:
    <<: *ubuntu16
    environment:
      CC: /usr/bin/gcc-4.8
      CXX: /usr/bin/g++-4.8
      PYVER: "2.7"
      CMAKE_BIN: /opt/cmake-2.8.12/bin
      ENABLE_MPI: ON
      ENABLE_TBB: ON
      ENABLE_CUDA: OFF
      BUILD_VALIDATION: OFF
      BUILD_JIT: OFF
      OMP_NUM_THREADS: 3
    <<: *build_and_test

  gcc54-py35-cm35-mpi-tbb3:
    <<: *ubuntu16
    environment:
      CC: /usr/bin/gcc
      CXX: /usr/bin/g++
      PYVER: "3.5"
      CMAKE: /usr/bin/cmake
      ENABLE_MPI: ON
      ENABLE_TBB: ON
      ENABLE_CUDA: OFF
      BUILD_VALIDATION: OFF
      BUILD_JIT: ON
      OMP_NUM_THREADS: 3
    <<: *build_and_test

  clang38-py35-cm35-mpi-tbb3:
    <<: *ubuntu16
    environment:
      CC: /usr/bin/clang
      CXX: /usr/bin/clang++
      PYVER: "3.5"
      CMAKE: /usr/bin/cmake
      ENABLE_MPI: ON
      ENABLE_TBB: ON
      ENABLE_CUDA: OFF
      BUILD_VALIDATION: OFF
      BUILD_JIT: ON
      OMP_NUM_THREADS: 3
    <<: *build_and_test

  gcc6-py36-cm310-mpi:
    <<: *ubuntu18
    environment:
      CC: /usr/bin/gcc-6
      CXX: /usr/bin/g++-6
      PYVER: "3.6"
      CMAKE: /usr/bin/cmake
      ENABLE_MPI: ON
      ENABLE_TBB: OFF
      ENABLE_CUDA: OFF
      BUILD_VALIDATION: OFF
      BUILD_JIT: ON
      OMP_NUM_THREADS: 3
    <<: *build_and_test

  gcc7-py36-cm310-mpi-tbb3:
    <<: *ubuntu18
    environment:
      CC: /usr/bin/gcc-7
      CXX: /usr/bin/g++-7
      PYVER: "3.6"
      CMAKE: /usr/bin/cmake
      ENABLE_MPI: ON
      ENABLE_TBB: ON
      ENABLE_CUDA: OFF
      BUILD_VALIDATION: OFF
      BUILD_JIT: ON
      OMP_NUM_THREADS: 3
    <<: *build_and_test

  gcc8-py36-cm310-mpi-tbb3:
    <<: *ubuntu18
    environment:
      CC: /usr/bin/gcc-8
      CXX: /usr/bin/g++-8
      PYVER: "3.6"
      CMAKE: /usr/bin/cmake
      ENABLE_MPI: ON
      ENABLE_TBB: ON
      ENABLE_CUDA: OFF
      BUILD_VALIDATION: OFF
      BUILD_JIT: ON
      OMP_NUM_THREADS: 3
    <<: *build_and_test

  clang4-py36-cm310-tbb3:
    <<: *ubuntu18
    environment:
      CC: /usr/bin/clang-4.0
      CXX: /usr/bin/clang++-4.0
      PYVER: "3.6"
      CMAKE: /usr/bin/cmake
      ENABLE_MPI: OFF
      ENABLE_TBB: ON
      ENABLE_CUDA: OFF
      BUILD_VALIDATION: OFF
      BUILD_JIT: ON
      OMP_NUM_THREADS: 3
    <<: *build_and_test

  clang5-py36-cm310-mpi-tbb3:
    <<: *ubuntu18
    environment:
      CC: /usr/bin/clang-5.0
      CXX: /usr/bin/clang++-5.0
      PYVER: "3.6"
      CMAKE: /usr/bin/cmake
      ENABLE_MPI: ON
      ENABLE_TBB: ON
      ENABLE_CUDA: OFF
      BUILD_VALIDATION: OFF
      BUILD_JIT: ON
      OMP_NUM_THREADS: 3
    <<: *build_and_test

  clang6-py36-cm310-mpi-tbb3:
    <<: *ubuntu18
    environment:
      CC: /usr/bin/clang-6.0
      CXX: /usr/bin/clang++-6.0
      PYVER: "3.6"
      CMAKE: /usr/bin/cmake
      ENABLE_MPI: ON
      ENABLE_TBB: ON
      ENABLE_CUDA: OFF
      BUILD_VALIDATION: OFF
      BUILD_JIT: ON
      OMP_NUM_THREADS: 3
    <<: *build_and_test

  sphinx-docs:
    <<: *ubuntu18
    steps:
      - *load_code
      - run:
          name: Run Sphinx
          working_directory: code/sphinx-doc
          command: sphinx-build -b html -d _build/doctrees -W -n . build/html

workflows:
  version: 2
  workflow:
    jobs:
      - gcc48-py27-cm28-mpi-tbb3
      - gcc54-py35-cm35-mpi-tbb3
      - clang38-py35-cm35-mpi-tbb3
      - gcc6-py36-cm310-mpi
      - gcc7-py36-cm310-mpi-tbb3
      - gcc8-py36-cm310-mpi-tbb3
      - clang4-py36-cm310-tbb3
      - clang5-py36-cm310-mpi-tbb3
      - clang6-py36-cm310-mpi-tbb3
      - sphinx-docs
